register_mahasiswa/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'), 
    url(r'^registermahasiswa/submit/$', register_mahasiswa, name='register-mhs'),


]

simbion16/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView 
from django.contrib import admin
import login.urls as login
import home.urls as home
import register_mahasiswa.urls as registermahasiswa
import register_donatur.urls as registerdonatur
import register_yayasan.urls as registeryayasan
import register_individu.urls as registerindividu
import description.urls as description
import register_skema_beasiswa.urls as registersb
import list_beasiswa.urls as listbeasiswa
import calon_penerima.urls as calonpenerima 
import daftar_calon.urls as daftarcalon

from home.views import index as index_login

urlpatterns = [
    url(r'^$', include(home,namespace='home')),
    #url(r'^$', RedirectView.as_view(url="/home/",permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login,namespace='login')),
    url(r'^registermahasiswa/', include(registermahasiswa,namespace='registermahasiswa')),
    url(r'^registerdonatur/', include(registerdonatur,namespace='registerdonatur')),
    url(r'^registeryayasan/', include(registeryayasan,namespace='registeryayasan')),
    url(r'^registerindividu/', include(registerindividu,namespace='registerindividu')),
    url(r'^description/', include(description,namespace='description')),
    url(r'^registersb/', include(registersb,namespace='registersb')),
    url(r'^listbeasiswa/', include(listbeasiswa,namespace='listbeasiswa')),
    url(r'^calonpenerima/', include(calonpenerima,namespace='calonpenerima')),
    url(r'^daftarcalon/', include(daftarcalon,namespace='daftarcalon'))
]

urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView 
from django.contrib import admin
import login.urls as login
import home.urls as home
import register_mahasiswa.urls as registermahasiswa
import register_donatur.urls as registerdonatur
import register_yayasan.urls as registeryayasan
import register_individu.urls as registerindividu
import description.urls as description
import register_skema_beasiswa.urls as registersb
import list_beasiswa.urls as listbeasiswa
import calon_penerima.urls as calonpenerima 
import daftar_calon.urls as daftarcalon

from home.views import index as index_login

urlpatterns = [
    url(r'^$', include(home,namespace='home')),
    #url(r'^$', RedirectView.as_view(url="/home/",permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login,namespace='login')),
    url(r'^registermahasiswa/', include(registermahasiswa,namespace='registermahasiswa')),
    url(r'^registerdonatur/', include(registerdonatur,namespace='registerdonatur')),
    url(r'^registeryayasan/', include(registeryayasan,namespace='registeryayasan')),
    url(r'^registerindividu/', include(registerindividu,namespace='registerindividu')),
    url(r'^description/', include(description,namespace='description')),
    url(r'^registersb/', include(registersb,namespace='registersb')),
    url(r'^listbeasiswa/', include(listbeasiswa,namespace='listbeasiswa')),
    url(r'^calonpenerima/', include(calonpenerima,namespace='calonpenerima')),
    url(r'^daftarcalon/', include(daftarcalon,namespace='daftarcalon'))
]

register_mahasiswa/models.py
from django.db import models

register_mahasiswa/forms.py
from django import forms
from .models import *

class RegisterFormMahasiswa(forms.Form):
    error_message = {
        'required': 'This field is required to fill',
    }

    username = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Username',
    }

    password = {
        'type': 'password',
        'class': 'form-control',
        'placeholder': 'Enter Password',
    }

    npm = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter NPM',
    }
 
    email = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Email',
    }

    nama = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Full Name',
    }

    no_hp = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Phone Number',
    }

    alamat = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Address',
    }

    domisili = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Domicile',
    }

    bank = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Bank Institute',
    }

    rekening = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Account Number',
    }

    pemilik = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Owner Name',
    }
    
    username = forms.CharField(label='Username', required=True, max_length=50, widget=forms.TextInput(attrs=username))
    password = forms.CharField(label='Password', required=True, max_length=50, widget=forms.TextInput(attrs=password))
    npm = forms.CharField(label='NPM', required=True, max_length=50, widget=forms.TextInput(attrs=npm))
    email = forms.CharField(label='Email', required=True, max_length=50, widget=forms.TextInput(attrs=email))
    nama = forms.CharField(label='Nama Lengkap', required=True, max_length=50, widget=forms.TextInput(attrs=nama))
    no_telp = forms.CharField(label='Nomor Telepon', required=False,max_length=50, widget=forms.TextInput(attrs=no_hp))
    alamat_tinggal = forms.CharField(label='Alamat Tempat Tinggal', required=True,max_length=50, widget=forms.TextInput(attrs=alamat))
    alamat_domisili = forms.CharField(label='Alamat Domisili', required=True, max_length=50, widget=forms.TextInput(attrs=domisili))
    nama_bank = forms.CharField(label='Instansi Bank', required=True, max_length=50, widget=forms.TextInput(attrs=bank))
    no_rekening = forms.CharField(label='Nomor Rekening', required=True, max_length=50, widget=forms.TextInput(attrs=rekening))
    nama_pemilik = forms.CharField(label='Nama Pemilik Rekening', required=True, max_length=50, widget=forms.TextInput(attrs=pemilik))

register_mahasiswa/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from .forms import *
from django.db import connection
from django.contrib import messages
# Create your views here.

def index(request):
    response = {}
    response['form_regmhs'] = RegisterFormMahasiswa
    return render(request, 'registermhs_landing.html', response)

@csrf_exempt
def register_mahasiswa(request): 

	form = RegisterFormMahasiswa(data=request.POST)

	if (request.method == 'POST' and form.is_valid()):
		cursor = connection.cursor()
	
		username = request.POST.get('username', False)
		password = request.POST.get('password', False)
		npm =request.POST.get('npm', False)
		email = request.POST.get('email', False)
		nama = request.POST.get('nama', False)
		no_telp = request.POST.get('no_telp', False)
		alamat_tinggal = request.POST.get('alamat_tinggal', False)
		alamat_domisili = request.POST.get('alamat_domisili', False)
		nama_bank = request.POST.get('nama_bank', False)
		no_rekening = request.POST.get('no_rekening', False)
		nama_pemilik = request.POST.get('nama_pemilik', False)

		query_pengguna = "insert into PENGGUNA (username, password, role) values ("+"'"+str(username)+"'"+", "+"'"+str(password)+"'"+", "+"'"+"mahasiswa"+"')"
		cursor.execute(query_pengguna)

		query_mhs = "insert into MAHASISWA (npm, email, nama, no_telp, alamat_tinggal, alamat_domisili, nama_bank, no_rekening, nama_pemilik, username) values ("+"'"+str(npm)+"'"+", "+"'"+str(email)+"'"+", "+"'"+str(nama)+"'"+", "+"'"+str(no_telp)+"'"+", "+"'"+str(alamat_tinggal)+"'"+", "+"'"+str(alamat_domisili)+"'"+", "+"'"+str(nama_bank)+"'"+", "+"'"+str(no_rekening)+"'"+", "+"'"+str(nama_pemilik)+"'"+", "+"'"+str(username)+"')"
		cursor.execute(query_mhs)

		return HttpResponseRedirect(reverse('login:index'))
	else:
		return HttpResponse("null")

register_mahasiswa/templates/registermhs_landing.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/registermhs.css' %}">
	<title>Register Mahasiswa</title>
</head>
<body>
  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-5">
          <div class="card" style="background-color: #F4FFFD; border: none;">
            <div class="card-body">
                <h1>Register as Mahasiswa</h1>
                <p>Please fill in this form to create an account as Mahasiswa.</p>
                <span style="color: red">*Required</span>
                <hr>
                
                <form method="POST" action="{% url 'registermahasiswa:register-mhs' %}">

                    <label for="{{ form_regmhs.username.id_for_label }}">{{form_regmhs.username.label}}<span style="color:red">*</span></label>
                      {{form_regmhs.username}}

                    <label for="{{ form_regmhs.password.id_for_label }}">{{form_regmhs.password.label}}<span style="color:red">*</span></label>
                      {{form_regmhs.password}}

                    <label for="{{ form_regmhs.npm.id_for_label }}">{{form_regmhs.npm.label}}<span style="color:red">*</span></label>
                      {{form_regmhs.npm}}

                    <label for="{{ form_regmhs.email.id_for_label }}">{{form_regmhs.email.label}}<span style="color:red">*</span></label>
                      {{form_regmhs.email}}

                    <label for="{{ form_regmhs.nama.id_for_label }}">{{form_regmhs.nama.label}}<span style="color:red">*</span></label>
                      {{form_regmhs.nama}}

                    <label for="{{ form_regmhs.no_telp.id_for_label }}">{{form_regmhs.no_telp.label}}</label>
                      {{form_regmhs.no_telp}}

                    <label for="{{ form_regmhs.alamat_tinggal.id_for_label }}">{{form_regmhs.alamat_tinggal.label}}<span style="color:red">*</span></label>
                      {{form_regmhs.alamat_tinggal}}

                    <label for="{{ form_regmhs.alamat_domisili.id_for_label }}">{{form_regmhs.alamat_domisili.label}}<span style="color:red">*</span></label>
                      {{form_regmhs.alamat_domisili}}

                    <label for="{{ form_regmhs.nama_bank.id_for_label }}">{{form_regmhs.nama_bank.label}}<span style="color:red">*</span></label>
                      {{form_regmhs.nama_bank}}

                    <label for="{{ form_regmhs.no_rekening.id_for_label }}">{{form_regmhs.no_rekening.label}}<span style="color:red">*</span></label>
                      {{form_regmhs.no_rekening}}

                    <label for="{{ form_regmhs.nama_pemilik.id_for_label }}">{{form_regmhs.nama_pemilik.label}}<span style="color:red">*</span></label>
                      {{form_regmhs.nama_pemilik}}


                    <div class="clearfix">
                      <button type="submit" class="signupbtn btn-primary">CREATE ACCOUNT</button>
                    </div>
              
                    <div class="container" style="margin-bottom: 50px;" >
                      <span style="float: right;">Already have an account?
                    	<a class="btn navbar-btn ml-2 text-white btn-secondary" href='/login/'>
                    	<i class="fa d-inline fa-lg fa-user-circle-o"></i>&nbsp;Login</a>
                      </span>
                    </div>

                </form>
                </div>
                </div>
                </div>
                </div>
                </div>
                </div>
              

</body>
</html>
{% endblock %}