register_skema_beasiswa/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    #url(r'^$', index, name='index'),
    url(r'^buat_beasiswa_baru/', baru, name='baru'),
    url(r'^buat_beasiswa_dari_paket/', paket, name='paket'),

    url(r'^buat_beasiswa_baru/register/submit/$', register_baru, name='register-baru'),


]

simbion16/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView 
from django.contrib import admin
import login.urls as login
import home.urls as home
import register_mahasiswa.urls as registermahasiswa
import register_donatur.urls as registerdonatur
import register_yayasan.urls as registeryayasan
import register_individu.urls as registerindividu
import description.urls as description
import register_skema_beasiswa.urls as registersb
import list_beasiswa.urls as listbeasiswa
import calon_penerima.urls as calonpenerima 
import daftar_calon.urls as daftarcalon

from home.views import index as index_login

urlpatterns = [
    url(r'^$', include(home,namespace='home')),
    #url(r'^$', RedirectView.as_view(url="/home/",permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login,namespace='login')),
    url(r'^registermahasiswa/', include(registermahasiswa,namespace='registermahasiswa')),
    url(r'^registerdonatur/', include(registerdonatur,namespace='registerdonatur')),
    url(r'^registeryayasan/', include(registeryayasan,namespace='registeryayasan')),
    url(r'^registerindividu/', include(registerindividu,namespace='registerindividu')),
    url(r'^description/', include(description,namespace='description')),
    url(r'^registersb/', include(registersb,namespace='registersb')),
    url(r'^listbeasiswa/', include(listbeasiswa,namespace='listbeasiswa')),
    url(r'^calonpenerima/', include(calonpenerima,namespace='calonpenerima')),
    url(r'^daftarcalon/', include(daftarcalon,namespace='daftarcalon'))
]

urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView 
from django.contrib import admin
import login.urls as login
import home.urls as home
import register_mahasiswa.urls as registermahasiswa
import register_donatur.urls as registerdonatur
import register_yayasan.urls as registeryayasan
import register_individu.urls as registerindividu
import description.urls as description
import register_skema_beasiswa.urls as registersb
import list_beasiswa.urls as listbeasiswa
import calon_penerima.urls as calonpenerima 
import daftar_calon.urls as daftarcalon

from home.views import index as index_login

urlpatterns = [
    url(r'^$', include(home,namespace='home')),
    #url(r'^$', RedirectView.as_view(url="/home/",permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login,namespace='login')),
    url(r'^registermahasiswa/', include(registermahasiswa,namespace='registermahasiswa')),
    url(r'^registerdonatur/', include(registerdonatur,namespace='registerdonatur')),
    url(r'^registeryayasan/', include(registeryayasan,namespace='registeryayasan')),
    url(r'^registerindividu/', include(registerindividu,namespace='registerindividu')),
    url(r'^description/', include(description,namespace='description')),
    url(r'^registersb/', include(registersb,namespace='registersb')),
    url(r'^listbeasiswa/', include(listbeasiswa,namespace='listbeasiswa')),
    url(r'^calonpenerima/', include(calonpenerima,namespace='calonpenerima')),
    url(r'^daftarcalon/', include(daftarcalon,namespace='daftarcalon'))
]

register_skema_beasiswa/models.py
from django.db import models

# Create your models here.

register_skema_beasiswa/forms.py
from django import forms

class RegisterFormBaru(forms.Form):
    error_message = {
        'required': 'This field is required to fill',
    }

    kode = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Kode',
    }

    nama = {
        'type': 'password',
        'class': 'form-control',
        'placeholder': 'Enter Nama',
    }

    jenis = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Jenis',
    }
 
    deskripsi = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Deskripsi',
    }

    syarat = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Syarat',
    }
    
    kode = forms.CharField(label='Kode', required=True, max_length=50, widget=forms.TextInput(attrs=kode))
    nama = forms.CharField(label='Nama', required=True, max_length=50, widget=forms.TextInput(attrs=nama))
    jenis = forms.CharField(label='Jenis', required=True, max_length=50, widget=forms.TextInput(attrs=jenis))
    deskripsi = forms.CharField(label='Deskripsi', required=True, max_length=50, widget=forms.TextInput(attrs=deskripsi))
    syarat = forms.CharField(label='Syarat', required=True, max_length=50, widget=forms.TextInput(attrs=syarat))

register_skema_beasiswa/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from .forms import *
from django.db import connection
from django.contrib import messages

# Create your views here.

def baru(request):
    response = {}
    return render(request, 'buat_beasiswa_baru.html', response)

@csrf_exempt
def register_baru(request):
    form = RegisterFormBaru(data=request.POST)

    if (request.method == 'POST' and form.is_valid()):
        cursor = connection.cursor()

        kode = request.POST.get('kode', False)
        nama = request.POST.get('nama', False)
        jenis =request.POST.get('jenis', False)
        deskripsi = request.POST.get('deskripsi', False)
        syarat = request.POST.get('syarat', False)

        query_skema_beasiswa = "insert into skema_beasiswa (kode, nama, jenis, deskripsi) values ("+"'"+str(kode)+"'"+", "+"'"+str(nama)+"'"+", "+"'"+str(jenis)+"'"+", "+"'"+str(deskripsi)+"')"
        cursor.execute(query_skema_beasiswa)

        query_syarat_beasiswa = "insert into syarat_beasiswa (kode_beasiswa, syarat) values ("+"'"+str(kode)+"'"+", "+"'"+str(syarat)+"')"
        cursor.execute(query_syarat_beasiswa)

        return HttpResponseRedirect(reverse('home:index'))
    else:
        return HttpResponse("null")

def paket(request):
    response = {}
    return render(request, 'buat_beasiswa_dari_paket.html', response)

register_skema_beasiswa/templates/buat_beasiswa_baru.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

<!DOCTYPE html>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/registersb.css' %}">
    <title>Pendaftaran Paket Beasiswa</title>
</head>

<form method="POST" action="{% url 'registersb:register-baru' %}">
  <div class="container">
    <h1>Form Pendaftaran Paket Beasiswa</h1>
    <p>Please fill in this form to Pendaftaran Paket Beasiswa.</p>
    <span style="color: red">*Required</span>
    <hr>

    <label for="kode"><b>Kode<span style="color: red"> *</span></b></label>
    <input type="text" placeholder="Enter Kode" name="kode" required>

    <label for="identitas"><b>Nama Paket Beasiswa<span style="color: red"> *</span></b></label>
    <input type="text" placeholder="Enter Nama Paket Beasiswa" name="nama_paket_beasiswa" required>

    <label for="jenis_paket_beasiswa"><b>Jenis Paket Beasiswa<span style="color: red"> *</span></b></label>
    <input type="text" placeholder="Enter Jenis Paket Beasiswa" name="jenis_paket_beasiswa" required>

    <label for="description"><b>Deksripsi<span style="color: red"> *</span></b></label>
    <input type="text" placeholder="Enter Deksripsi" name="description" required>

    <label for="syarat_beasiswa"><b>Syarat Beasiswa<span style="color: red"> *</span></b></label>
    <input type="text" placeholder="Enter Syarat Beasiswa" name="syarat_beasiswa" required>

    <div class="clearfix">
      <button type="submit" class="signupbtn btn-primary">SUBMIT</button>
    </div>
 </div>

</form>

{% endblock %}

register_skema_beasiswa/templates/buat_beasiswa_dari_paket.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

<!DOCTYPE html>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/registersb.css' %}">
    <title>Pendaftaran Tambah Beasiswa Dari Paket</title>
</head>

<form action="action_page.php" style="margin-left: 350px; margin-right: 450px; margin-top: 30px;">
  <div class="container">
    <h1>Form Pendaftaran Tambah Beasiswa Dari Paket</h1>
    <p>Please fill in this form to Tambah Beasiswa Dari Paket.</p>
    <span style="color: red">*Required</span>
    <hr>

    <label for="kode"><b>Kode<span style="color: red"> *</span></b></label>
    <input type="text" placeholder="Enter Kode" name="kode" required>

    <label for="nomor_urut_beasiswa"><b>Nomor Urut<span style="color: red"> *</span></b></label>
    <input type="text" placeholder="Enter Nomor Urut" name="nomor_urut_beasiswa" required>

    <label for="tanggal_mulai_daftar"><b>Tanggal Mulai Pendaftaran<span style="color: red"> *</span></b></label>
    <input type="date" placeholder="Enter Tanggal Mulai Pendaftaran" name="tanggal_mulai_daftar" required>

    <label for="tanggal_tutup_daftar"><b>Tanggal Tutup Pendaftaran<span style="color: red"> *</span></b></label>
    <input type="date" placeholder="Enter Tanggal Tutup Pendaftaran" name="tanggal_tutup_daftar" required>

    <div class="clearfix">
      <button type="submit" class="signupbtn btn-primary">SUBMIT</button>
    </div>
 </div>

</form>

{% endblock %}