register_yayasan/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^registeryayasan/submit/$', register_yayasan, name='register_yayasan'),

]

simbion16/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView 
from django.contrib import admin
import login.urls as login
import home.urls as home
import register_mahasiswa.urls as registermahasiswa
import register_donatur.urls as registerdonatur
import register_yayasan.urls as registeryayasan
import register_individu.urls as registerindividu
import description.urls as description
import register_skema_beasiswa.urls as registersb
import list_beasiswa.urls as listbeasiswa
import calon_penerima.urls as calonpenerima 
import daftar_calon.urls as daftarcalon

from home.views import index as index_login

urlpatterns = [
    url(r'^$', include(home,namespace='home')),
    #url(r'^$', RedirectView.as_view(url="/home/",permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login,namespace='login')),
    url(r'^registermahasiswa/', include(registermahasiswa,namespace='registermahasiswa')),
    url(r'^registerdonatur/', include(registerdonatur,namespace='registerdonatur')),
    url(r'^registeryayasan/', include(registeryayasan,namespace='registeryayasan')),
    url(r'^registerindividu/', include(registerindividu,namespace='registerindividu')),
    url(r'^description/', include(description,namespace='description')),
    url(r'^registersb/', include(registersb,namespace='registersb')),
    url(r'^listbeasiswa/', include(listbeasiswa,namespace='listbeasiswa')),
    url(r'^calonpenerima/', include(calonpenerima,namespace='calonpenerima')),
    url(r'^daftarcalon/', include(daftarcalon,namespace='daftarcalon'))
]

urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView 
from django.contrib import admin
import login.urls as login
import home.urls as home
import register_mahasiswa.urls as registermahasiswa
import register_donatur.urls as registerdonatur
import register_yayasan.urls as registeryayasan
import register_individu.urls as registerindividu
import description.urls as description
import register_skema_beasiswa.urls as registersb
import list_beasiswa.urls as listbeasiswa
import calon_penerima.urls as calonpenerima 
import daftar_calon.urls as daftarcalon

from home.views import index as index_login

urlpatterns = [
    url(r'^$', include(home,namespace='home')),
    #url(r'^$', RedirectView.as_view(url="/home/",permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login,namespace='login')),
    url(r'^registermahasiswa/', include(registermahasiswa,namespace='registermahasiswa')),
    url(r'^registerdonatur/', include(registerdonatur,namespace='registerdonatur')),
    url(r'^registeryayasan/', include(registeryayasan,namespace='registeryayasan')),
    url(r'^registerindividu/', include(registerindividu,namespace='registerindividu')),
    url(r'^description/', include(description,namespace='description')),
    url(r'^registersb/', include(registersb,namespace='registersb')),
    url(r'^listbeasiswa/', include(listbeasiswa,namespace='listbeasiswa')),
    url(r'^calonpenerima/', include(calonpenerima,namespace='calonpenerima')),
    url(r'^daftarcalon/', include(daftarcalon,namespace='daftarcalon'))
]

register_yayasan/models.py
from django.db import models

register_yayasan/forms.py
from django import forms
from .models import *

class RegisterFormYayasan(forms.Form):
    error_message = {
        'required': 'This field is required to fill',
    }

    username = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Username',
    }

    password = {
        'type': 'password',
        'class': 'form-control',
        'placeholder': 'Enter Password',
    }

    no_identitas = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter ID Number',
    }

    no_sk_yayasan = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Foundation Number',
    }
 
    email = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Email',
    }

    nama = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Foundation Name',
    }

    no_telp = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Phone Number',
    }

    npwp = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Account Number',
    }

    alamat = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Address',
    }

    
    
    username = forms.CharField(label='Username', required=True, max_length=50, widget=forms.TextInput(attrs=username))
    password = forms.CharField(label='Password', required=True, max_length=50, widget=forms.TextInput(attrs=password))
    no_identitas = forms.CharField(label='Nomor Identitas', required=True, max_length=50, widget=forms.TextInput(attrs=no_identitas))
    no_sk_yayasan = forms.CharField(label='Nomor SK Yayasan', required=True, max_length=50, widget=forms.TextInput(attrs=no_sk_yayasan))
    email = forms.CharField(label='Email', required=True, max_length=50, widget=forms.TextInput(attrs=email))
    nama = forms.CharField(label='Nama Yayasan', required=True, max_length=50, widget=forms.TextInput(attrs=nama))
    no_telp = forms.CharField(label='Nomor Telepon CP', required=False,max_length=50, widget=forms.TextInput(attrs=no_telp))
    npwp = forms.CharField(label='NPWP', required=True, max_length=50, widget=forms.TextInput(attrs=npwp))
    alamat = forms.CharField(label='Alamat Yayasan', required=True,max_length=50, widget=forms.TextInput(attrs=alamat))
    

register_yayasan/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from .forms import *
from django.db import connection
from django.contrib import messages

# Create your views here.
def index(request):
	response = {}
	response['form_regyys'] = RegisterFormYayasan
	return render(request, 'yayasan_landing.html', response)

@csrf_exempt
def register_yayasan(request):
	form = RegisterFormYayasan(data=request.POST)

	if (request.method == 'POST' and form.is_valid()):
		cursor = connection.cursor()

		username = request.POST.get('username', False)
		password = request.POST.get('password', False)
		no_identitas =request.POST.get('no_identitas', False)
		no_sk_yayasan =request.POST.get('no_sk_yayasan', False)
		email = request.POST.get('email', False)
		nama = request.POST.get('nama', False)
		no_telp = request.POST.get('no_telp', False)
		npwp = request.POST.get('npwp', False)
		alamat = request.POST.get('alamat', False)

		query_pengguna = "insert into PENGGUNA (username, password, role) values ("+"'"+str(username)+"'"+", "+"'"+str(password)+"'"+", "+"'"+"donatur"+"')"
		cursor.execute(query_pengguna)

		query_dnt = "insert into DONATUR (nomor_identitas, email, nama, npwp, no_telp, alamat, username) values ("+"'"+str(no_identitas)+"'"+", "+"'"+str(email)+"'"+", "+"'"+str(nama)+"'"+", "+"'"+str(npwp)+"'"+", "+"'"+str(no_telp)+"'"+", "+"'"+str(alamat)+"'"+", "+"'"+str(username)+"')"
		cursor.execute(query_dnt)

		query_yys = "insert into YAYASAN (no_sk_yayasan, email, nama, no_telp_cp, nomor_identitas_donatur) values ("+"'"+str(no_sk_yayasan)+"'"+", "+"'"+str(email)+"'"+", "+"'"+str(nama)+"'"+", "+"'"+str(no_telp)+"'"+", "+"'"+str(no_identitas)+"')"
		cursor.execute(query_yys)

		return HttpResponseRedirect(reverse('login:index'))
	else:
		return HttpResponse("null")

register_yayasan/templates/yayasan_landing.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/yayasan.css' %}">
	<title>Register Donatur</title>
</head>

<body>
<div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6">
          <div class="card" style="background-color: #F4FFFD; border: none;">
            <div class="card-body">
                <h1>Register as Donatur Yayasan</h1>
                <p>Please fill in this form to create an account as Donatur Yayasan.</p>
                <span style="color: red">*Required</span>
                <hr>
                
                <form method="POST" action="{% url 'registeryayasan:register_yayasan' %}">
                  
                    <label for="{{ form_regyys.username.id_for_label }}">{{form_regyys.username.label}}<span style="color:red">*</span></label>
                    {{form_regyys.username}}

                   <label for="{{ form_regyys.password.id_for_label }}">{{form_regyys.password.label}}<span style="color:red">*</span></label>
                    {{form_regyys.password}}

                    <label for="{{ form_regyys.no_identitas.id_for_label }}">{{form_regyys.no_identitas.label}}<span style="color:red">*</span></label>
                    {{form_regyys.no_identitas}}

                     <label for="{{ form_regyys.no_sk_yayasan.id_for_label }}">{{form_regyys.no_sk_yayasan.label}}<span style="color:red">*</span></label>
                    {{form_regyys.no_sk_yayasan}}

                     <label for="{{ form_regyys.email.id_for_label }}">{{form_regyys.email.label}}<span style="color:red">*</span></label>
                    {{form_regyys.email}}

                     <label for="{{ form_regyys.nama.id_for_label }}">{{form_regyys.nama.label}}<span style="color:red">*</span></label>
                    {{form_regyys.nama}}

                     <label for="{{ form_regyys.no_telp.id_for_label }}">{{form_regyys.no_telp.label}}</span></label>
                    {{form_regyys.no_telp}}

                     <label for="{{ form_regyys.npwp.id_for_label }}">{{form_regyys.npwp.label}}<span style="color:red">*</span></label>
                    {{form_regyys.npwp}}

                     <label for="{{ form_regyys.alamat.id_for_label }}">{{form_regyys.alamat.label}}<span style="color:red">*</span></label>
                    {{form_regyys.alamat}}


                    <div class="clearfix">
                      <button type="submit" class="signupbtn btn-primary">CREATE ACCOUNT</button>
                    </div>
                 

                     <div class="container" style="margin-bottom: 50px;" >
                    	<span style="float: right;">Already have an account?
                    	   <a class="btn navbar-btn ml-2 text-white btn-secondary" href='/login/'>
                    	   <i class="fa d-inline fa-lg fa-user-circle-o"></i>&nbsp;Login</a>
                    	</span>
                     </div>
                </form>
            </div>
            </div>
            </div>
            </div>
            </div>
            </div>
</body>

</html>
{% endblock %}