register_individu/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^registerindividu/submit/$', register_individu, name='register_individu'),
]

simbion16/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView 
from django.contrib import admin
import login.urls as login
import home.urls as home
import register_mahasiswa.urls as registermahasiswa
import register_donatur.urls as registerdonatur
import register_yayasan.urls as registeryayasan
import register_individu.urls as registerindividu
import description.urls as description
import register_skema_beasiswa.urls as registersb
import list_beasiswa.urls as listbeasiswa
import calon_penerima.urls as calonpenerima 
import daftar_calon.urls as daftarcalon

from home.views import index as index_login

urlpatterns = [
    url(r'^$', include(home,namespace='home')),
    #url(r'^$', RedirectView.as_view(url="/home/",permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login,namespace='login')),
    url(r'^registermahasiswa/', include(registermahasiswa,namespace='registermahasiswa')),
    url(r'^registerdonatur/', include(registerdonatur,namespace='registerdonatur')),
    url(r'^registeryayasan/', include(registeryayasan,namespace='registeryayasan')),
    url(r'^registerindividu/', include(registerindividu,namespace='registerindividu')),
    url(r'^description/', include(description,namespace='description')),
    url(r'^registersb/', include(registersb,namespace='registersb')),
    url(r'^listbeasiswa/', include(listbeasiswa,namespace='listbeasiswa')),
    url(r'^calonpenerima/', include(calonpenerima,namespace='calonpenerima')),
    url(r'^daftarcalon/', include(daftarcalon,namespace='daftarcalon'))
]

urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView 
from django.contrib import admin
import login.urls as login
import home.urls as home
import register_mahasiswa.urls as registermahasiswa
import register_donatur.urls as registerdonatur
import register_yayasan.urls as registeryayasan
import register_individu.urls as registerindividu
import description.urls as description
import register_skema_beasiswa.urls as registersb
import list_beasiswa.urls as listbeasiswa
import calon_penerima.urls as calonpenerima 
import daftar_calon.urls as daftarcalon

from home.views import index as index_login

urlpatterns = [
    url(r'^$', include(home,namespace='home')),
    #url(r'^$', RedirectView.as_view(url="/home/",permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login,namespace='login')),
    url(r'^registermahasiswa/', include(registermahasiswa,namespace='registermahasiswa')),
    url(r'^registerdonatur/', include(registerdonatur,namespace='registerdonatur')),
    url(r'^registeryayasan/', include(registeryayasan,namespace='registeryayasan')),
    url(r'^registerindividu/', include(registerindividu,namespace='registerindividu')),
    url(r'^description/', include(description,namespace='description')),
    url(r'^registersb/', include(registersb,namespace='registersb')),
    url(r'^listbeasiswa/', include(listbeasiswa,namespace='listbeasiswa')),
    url(r'^calonpenerima/', include(calonpenerima,namespace='calonpenerima')),
    url(r'^daftarcalon/', include(daftarcalon,namespace='daftarcalon'))
]

register_individu/models.py
from django.db import models

# Create your models here.

register_individu/forms.py
from django import forms
from .models import *

class RegisterFormIndividu(forms.Form):
    error_message = {
        'required': 'This field is required to fill',
    }

    username = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Username',
    }

    password = {
        'type': 'password',
        'class': 'form-control',
        'placeholder': 'Enter Password',
    }

    no_identitas = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter ID Number',
    }

    nik = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter NIK',
    }
 
    email = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Email',
    }

    nama = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Full Name',
    }

    npwp = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter NPWP',
    }

    no_telp = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Phone Number',
    }

    alamat = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter Address',
    }
    
    username = forms.CharField(label='Username', required=True, max_length=50, widget=forms.TextInput(attrs=username))
    password = forms.CharField(label='Password', required=True, max_length=50, widget=forms.TextInput(attrs=password))
    no_identitas = forms.CharField(label='Nomor Identitas', required=True, max_length=50, widget=forms.TextInput(attrs=no_identitas))
    nik = forms.CharField(label='NIK', required=True, max_length=50, widget=forms.TextInput(attrs=nik))
    email = forms.CharField(label='Email', required=True, max_length=50, widget=forms.TextInput(attrs=email))
    nama = forms.CharField(label='Nama Lengkap', required=True, max_length=50, widget=forms.TextInput(attrs=nama))
    npwp = forms.CharField(label='NPWP', required=True, max_length=50, widget=forms.TextInput(attrs=npwp))
    no_telp = forms.CharField(label='Nomor Telepon', required=False,max_length=50, widget=forms.TextInput(attrs=no_telp))
    alamat = forms.CharField(label='Alamat Lengkap', required=True,max_length=50, widget=forms.TextInput(attrs=alamat))
    

register_individu/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from .forms import *
from django.db import connection
from django.contrib import messages

# Create your views here.
def index(request):
    response = {}
    response['form_regind'] = RegisterFormIndividu
    return render(request, 'individu_landing.html', response)

@csrf_exempt
def register_individu(request):
	form = RegisterFormIndividu(data=request.POST)

	if (request.method == 'POST' and form.is_valid()):
		cursor = connection.cursor()

		username = request.POST.get('username', False)
		password = request.POST.get('password', False)
		no_identitas =request.POST.get('no_identitas', False)
		nik =request.POST.get('nik', False)
		email = request.POST.get('email', False)
		nama = request.POST.get('nama', False)
		npwp = request.POST.get('npwp', False)
		no_telp = request.POST.get('no_telp', False)
		alamat = request.POST.get('alamat', False)

		query_pengguna = "insert into PENGGUNA (username, password, role) values ("+"'"+str(username)+"'"+", "+"'"+str(password)+"'"+", "+"'"+"donatur"+"')"
		cursor.execute(query_pengguna)

		query_dnt = "insert into DONATUR (nomor_identitas, email, nama, npwp, no_telp, alamat, username) values ("+"'"+str(no_identitas)+"'"+", "+"'"+str(email)+"'"+", "+"'"+str(nama)+"'"+", "+"'"+str(npwp)+"'"+", "+"'"+str(no_telp)+"'"+", "+"'"+str(alamat)+"'"+", "+"'"+str(username)+"')"
		cursor.execute(query_dnt)

		query_ind = "insert into INDIVIDUAL_DONOR (nik, nomor_identitas_donatur) values ("+"'"+str(nik)+"'"+", "+"'"+str(no_identitas)+"')"
		cursor.execute(query_ind)

		return HttpResponseRedirect(reverse('login:index'))
	else:
		return HttpResponse("null")

register_individu/templates/individu_landing.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/individu.css' %}">
	<title>Register Donatur</title>
</head>

<body>
 <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6">
          <div class="card" style="background-color: #F4FFFD; border: none;">
            <div class="card-body">
                <h1>Register as Donatur Individu</h1>
                <p>Please fill in this form to create an account as Donatur Individu.</p>
                <span style="color: red">*Required</span>
                <hr>
                <form method="POST" action="{% url 'registerindividu:register_individu' %}">
                    
                    <label for="{{ form_regind.username.id_for_label }}">{{form_regind.username.label}}<span style="color:red">*</span></label>
                    {{form_regind.username}}

                    <label for="{{ form_regind.password.id_for_label }}">{{form_regind.password.label}}<span style="color:red">*</span></label>
                    {{form_regind.password}}

                    <label for="{{ form_regind.no_identitas.id_for_label }}">{{form_regind.no_identitas.label}}<span style="color:red">*</span></label>
                    {{form_regind.no_identitas}}

                     <label for="{{ form_regind.nik.id_for_label }}">{{form_regind.nik.label}}<span style="color:red">*</span></label>
                    {{form_regind.nik}}

                     <label for="{{ form_regind.email.id_for_label }}">{{form_regind.email.label}}<span style="color:red">*</span></label>
                    {{form_regind.email}}

                     <label for="{{ form_regind.nama.id_for_label }}">{{form_regind.nama.label}}<span style="color:red">*</span></label>
                    {{form_regind.nama}}

                    <label for="{{ form_regind.npwp.id_for_label }}">{{form_regind.npwp.label}}<span style="color:red">*</span></label>
                    {{form_regind.npwp}}

                     <label for="{{ form_regind.no_telp.id_for_label }}">{{form_regind.no_telp.label}}</span></label>
                    {{form_regind.no_telp}}

                     <label for="{{ form_regind.alamat.id_for_label }}">{{form_regind.alamat.label}}<span style="color:red">*</span></label>
                    {{form_regind.alamat}}

                    <div class="clearfix">
                      <button type="submit" class="signupbtn btn-primary">CREATE ACCOUNT</button>
                    </div>

                     <div class="container" style="margin-bottom: 50px;" >
                    	<span style="float: right;">Already have an account?
                    	   <a class="btn navbar-btn ml-2 text-white btn-secondary" href='/login/'>
                    	   <i class="fa d-inline fa-lg fa-user-circle-o"></i>&nbsp;Login</a>
                    	</span>
                     </div>

                </form>

            </div>
            </div>
            </div>
            </div>
            </div>
            </div>
                

</body>

</html>

{% endblock %}